"""The simulator: the C++ extension module, as Python sees it.

The module itself is built from src/socpuppet/bindings/core.cpp. This file
describes it to type checkers, which cannot read a compiled extension.
"""

from socpuppet.components import Script

def implementations() -> list[str]: ...
def global_quantum_in_picoseconds() -> int: ...

# (word size in bits, entry point, [(physical address, bytes), ...])
def read_elf(path: str) -> tuple[int, int, list[tuple[int, bytes]]]: ...

class Platform:
    def __init__(self, color_log: bool) -> None: ...
    def add(
        self, path: str, implementation: str, config: dict[str, int]
    ) -> None: ...
    def bind(self, source: str, sink: str, traced: bool) -> None: ...
    # Each record is (time in ps, source, sink, is_write, address, data, ok).
    def trace_records(
        self,
    ) -> list[tuple[int, str, str, bool, int, bytes, bool]]: ...
    def set_script(self, path: str, generator_function: Script) -> None: ...
    def uart_output(self, path: str) -> bytes: ...
    def ports(self, path: str) -> list[str]: ...
    def elaborate(self) -> None: ...
    def run(self) -> None: ...
    def set_quantum(self, picoseconds: int) -> None: ...
    def run_for(self, picoseconds: int) -> None: ...
    def step(self) -> bool: ...
    def picoseconds_to_next_activity(self) -> int | None: ...
    def time_in_picoseconds(self) -> int: ...
    def debug_read(
        self, via: str, address: int, length: int
    ) -> bytes | None: ...
    def debug_write(self, via: str, address: int, data: bytes) -> bool: ...
